import 'package:get/get_state_manager/src/simple/get_controllers.dart';

class PersonalHealthInsurerController extends GetxController {
  var son = 0;
  var Daughter = 0;
  var CityColorValueIndex = 0;
  var CarCityColorValueIndex = 10;
  List SelectedMembers = [];
  List SelectedMedicalHistory = [];
  List FinalNameWithAge = [];
  List CityName = [
    'Mumbai',
    'Pune',
    'Delhi',
    'Chennai',
    'Hyderabad',
    'Kochi',
    'Kolkata'
  ];
  List AgeList = [
    '3-12 Months',
    '1 Years',
    '2 Years',
    '3 Years',
    '4 Years',
    '5 Years',
    '6 Years',
    '7 Years',
    '8 Years',
    '9 Years',
    '10 Years',
    '11 Years',
    '12 Years',
    '13 Years',
    '14 Years',
    '15 Years',
    '16 Years',
    '17 Years',
    '18 Years',
    '19 Years',
    '20 Years',
    '21 Years',
    '22 Years',
    '23 Years',
    '24 Years',
    '25 Years',
    '26 Years',
    '27 Years',
    '28 Years',
    '29 Years',
    '30 Years',
    '31 Years',
    '32 Years',
    '33 Years',
    '34 Years',
    '35 Years',
    '36 Years',
    '37 Years',
    '38 Years',
    '39 Years',
    '40 Years',
    '41 Years',
    '42 Years',
    '43 Years',
    '44 Years',
    '45 Years',
    '46 Years',
    '47 Years',
    '48 Years',
    '49 Years',
    '50 Years',
    '51 Years',
    '52 Years',
    '53 Years',
    '54 Years',
    '55 Years',
    '56 Years',
    '57 Years',
    '58 Years',
    '59 Years',
    '60 Years',
    '61 Years',
    '62 Years',
    '63 Years',
    '64 Years',
    '65 Years',
    '66 Years',
    '67 Years',
    '68 Years',
    '69 Years',
    '70 Years',
    '71 Years',
    '72 Years',
    '73 Years',
    '74 Years',
    '75 Years',
    '76 Years',
    '77 Years',
    '78 Years',
    '79 Years',
    '80 Years',
    '81 Years',
    '82 Years',
    '83 Years',
    '84 Years',
    '85 Years',
    '86 Years',
    '87 Years',
    '88 Years',
    '89 Years',
    '90 Years',
    '91 Years',
    '92 Years',
    '93 Years',
    '94 Years',
    '95 Years',
    '96 Years',
    '97 Years',
    '98 Years',
    '99 Years',
    '100 Years'
  ];
}
